### ISSUE TITLE
Something wrong with magent/battle_v3 -- some agents doesn't do actions

### ISSUE THREAD

**Issue by yaorelax** [Farama-Foundation/PettingZoo#542] opened 2021-11-18 14:38 UTC
```
from pettingzoo.magent import battle_v3
from pettingzoo.utils import random_demo

env = battle_v3.env(map_size=20, minimap_mode=False, step_reward=-0.005,
                    dead_penalty=-0.1, attack_penalty=-0.1, attack_opponent_reward=0.2,
                    max_cycles=100000, extra_features=False)
env.reset()
random_demo(env, render=True, episodes=1)
```

After running for some time, some agents went on strike。

https://user-images.githubusercontent.com/53855240/142435576-08d25d2f-9b95-470a-8135-7f38780f229b.mp4

**Comment by benblack769** [comment] 2021-11-18 15:51
Thanks for pointing out this bug. Its hard to investigate this codebase, because it is written in c++ and is hard to debug, but I'll try to give it a look anyways.

**Comment by kkahadze** [comment] 2022-01-14 01:59
@benblack769 I am currently investigating this issue and I have been trying to learn more about it by recreating it in different ways. I learned that creating the environment with step_reward set to -0.015 made the agents stop going on strike. Also, I saw that these agents going on strike tended to happen near the edges and corners of the map, suggesting it may have something to do with the proximity to the walls.

I thought I could use the state() method described in magent.md to help me with this issue but I had trouble understanding the description. When recreating the environment in the issue and getting the state from the state method(), I got a 3d array of shape (20, 20, 5) which I don’t know how to interpret since I thought that there should only be 3 channels for the array returned. What do these channels returned by state() mean? Also, are there other ways of capturing the data from this environment that you might suggest?

Additionally, the simulations have been running slowly on my i5 Macbook Pro so, do you have any suggestions for running the Pygame environment faster? It seems as though the first few steps run fast, and then it gets much slower.

Thanks

**Comment by benblack769** [comment] 2022-01-14 21:12
The state space is documented here: https://www.pettingzoo.ml/magent/battle#state-space

If you could share your code, I might be able to give a pointer as to why it is running slowly.

**Comment by kkahadze** [comment] 2022-01-17 04:06
Here is my code.
```
from pettingzoo.magent import battle_v3
import random
from pettingzoo.utils import random_demo

def main():
    env = battle_v3.env(map_size=20, minimap_mode=False, step_reward=-0.005,
                        dead_penalty=-0.1, attack_penalty=-0.1, attack_opponent_reward=0.2,
                        max_cycles=100000, extra_features=False)
    env.reset()
    random_demo(env, render=True, episodes=1)

if __name__ == "__main__":
    main()
```

**Comment by benblack769** [comment] 2022-01-23 23:48
So the reason random_demo renders slowly is because it renders seperately for each agent:

In order to render faster, you can use the parallel interface:

```
par_env = battle_v3.parallel_env()
obs = par_env.reset()
for i in range(num_cycles):
	actions = {agent: par_env.action_space(agent).sample() for agent in par_env.agents if agent in done and not done[agent]}
	obs, rew, done, info = par_env.step(actions)
	par_env.render()
```

**Comment by benblack769** [comment] 2022-01-23 23:52
Its hard to imagine why changing `step_reward` will change the outcome of random actions. Some more investigation of what conditions this does and doesn't happen is needed. I suspect the issue is a buffer overrun issue, though I can't be sure.

**Comment by kkahadze** [comment] 2022-01-26 01:40
@benblack769 Can I not use agent_iter while running the parallel environment? I am getting "AttributeError: '_parallel_env' object has no attribute 'agent_iter'".

**Comment by kkahadze** [comment] 2022-01-31 23:46
@benblack769 Nevermind, I fixed that. I realized I did not need to use random_demo when running the parallel environment.

**Comment by jkterry1** [comment] 2022-04-13 17:13
Closing in favor of #653

**Closed by jkterry1** 2022-04-13 17:13 UTC
