### ISSUE TITLE
[Bug Report] ClipOutOfBoundsWrapper.step() AttributeError: 'int' object has no attribute 'shape'

### ISSUE THREAD

**Issue by luorq3** [Farama-Foundation/PettingZoo#888] opened 2023-02-27 04:34 UTC
### Describe the bug

When I using Ray.rllib to try 'pistonball_v6' env, it raise a AttrbuteError caused by `int.shape`. There is the fully stack tracing below:

File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/utils/actor_manager.py", line 183, in apply
    raise e
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/utils/actor_manager.py", line 174, in apply
    return func(self, *args, **kwargs)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/execution/rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 914, in sample
    batches = [self.input_reader.next()]
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
    batches = [self.get_data()]
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 379, in step
    self._base_env.send_actions(actions_to_send)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/env/multi_agent_env.py", line 656, in send_actions
    raise e
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/env/multi_agent_env.py", line 645, in send_actions
    obs, rewards, terminateds, truncateds, infos = env.step(agent_dict)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/ray/rllib/env/wrappers/pettingzoo_env.py", line 207, in step
    obss, rews, terminateds, truncateds, infos = self.par_env.step(action_dict)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/conversions.py", line 157, in step
    self.aec_env.step(actions[agent])
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/supersuit/utils/base_aec_wrapper.py", line 44, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 75, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 108, in step
    self.env.step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 75, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 108, in step
    self.env.step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/conversions.py", line 292, in step
    obss, rews, terminations, truncations, infos = self.env.step(self._actions)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/supersuit/generic_wrappers/utils/shared_wrapper_util.py", line 125, in step
    observations, rewards, terminations, truncations, infos = super().step(actions)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base_parallel.py", line 39, in step
    res = self.env.step(actions)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/conversions.py", line 157, in step
    self.aec_env.step(actions[agent])
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/supersuit/utils/base_aec_wrapper.py", line 44, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 75, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 108, in step
    self.env.step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/supersuit/utils/base_aec_wrapper.py", line 44, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 75, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 108, in step
    self.env.step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/supersuit/utils/base_aec_wrapper.py", line 44, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 75, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 108, in step
    self.env.step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 75, in step
    super().step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 108, in step
    self.env.step(action)
  File "/home/roots/anaconda3/envs/all/lib/python3.8/site-packages/pettingzoo/utils/wrappers/clip_out_of_bounds.py", line 31, in step
    space.shape == action.shape
AttributeError: 'int' object has no attribute 'shape'

### Code example

```shell
if __name__ == "__main__":
    env_name = "pistonball_v6"

    register_env(env_name, lambda config: ParallelPettingZooEnv(env_creator(config)))

    config = (
        PPOConfig()
        .rollouts(num_rollout_workers=4, rollout_fragment_length="auto")
        .training(
            train_batch_size=512,
            lr=2e-5,
            gamma=0.99,
            lambda_=0.9,
            use_gae=True,
            clip_param=0.4,
            grad_clip=None,
            entropy_coeff=0.1,
            vf_loss_coeff=0.25,
            sgd_minibatch_size=64,
            num_sgd_iter=10,
        )
        .environment(env=env_name, clip_actions=True)
        .debugging(log_level="ERROR")
        .framework(framework="torch")
        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )

    tune.run(
        "PPO",
        name="PPO",
        stop={"timesteps_total": 5000000},
        checkpoint_freq=10,
        local_dir="~/ray_results/" + env_name,
        config=config.to_dict(),
    )
```

### System info

env: pip
pettingzoo version: 1.22.3
ray version: 2.3.0
OS: Ubuntu 20.04.4 LTS

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment] 2023-03-14 20:51
It doesn't look like your code example is complete as it calls env_creator but that part is not shown, but either way the problem is that parallel envs can't take a single int as a step, they take actions for each agent for a single step() call, so it needs to be a numpy array of length `env.num_agents`. 

If you want working RLlib code try this out (should get merged soon, the tutorials are outdated and a few things have changed with both RLlib and pettingzoo since they were originally released): https://github.com/elliottower/PettingZoo/blob/rllib-tutorials/tutorials/Ray/rllib_pistonball.py

**Closed** 2023-05-12 17:15 UTC
Labels: bug
