### ISSUE TITLE
Error running tutorial: 'ProcConcatVec' object has no attribute 'pipes'

### ISSUE THREAD

**Issue by erickrf** [Farama-Foundation/PettingZoo#710] opened 2022-05-29 13:17 UTC
I'm running into an error with this long stack trace when I try to run the 13 line tutorial:

```
/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/erick/dev/rl/main_pettingzoo.py", line 22, in <module>
    env = ss.concat_vec_envs_v1(env, 8, num_cpus=4, base_class="stable_baselines3")
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/supersuit/vector/vector_constructors.py", line 60, in concat_vec_envs_v1
    vec_env = MakeCPUAsyncConstructor(num_cpus)(*vec_env_args(vec_env, num_vec_envs))
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/supersuit/vector/constructors.py", line 38, in constructor
    return ProcConcatVec(
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/supersuit/vector/multiproc_vec.py", line 144, in __init__
    proc.start()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <function ProcConcatVec.__del__ at 0x112cf1310>
Traceback (most recent call last):
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/supersuit/vector/multiproc_vec.py", line 210, in __del__
    for pipe in self.pipes:
AttributeError: 'ProcConcatVec' object has no attribute 'pipes'

```

Maybe the issue here is some mismatch in library versioning, but I found no reference to which `supersuit` version is supposed to run with the tutorial (or with the rest of the code). 

I am running python 3.9 with `supersuit` 3.4 and `pettingzoo` 1.18.1

**Comment by jjshoots** [comment] 2022-05-29 15:33
Hi @erickrf, the 13 lines code is actually supposed to work with the latest version of SS and PZ, and is also in [CI tests](https://github.com/Farama-Foundation/PettingZoo/blob/master/.github/workflows/linux-test.yml#L37). So this error is quite peculiar.

That said, I'll get someone to look into this.

**Comment by jjshoots** [comment] 2022-05-30 16:16
Hi @erickrf, did you have any luck with this? We've just checked internally that this error cannot be reproduced on our setup. What's your gym version btw?

Just for your reference, this is the setup we're running at the moment:

Ubuntu 20.04, Python 3.8.10

cffi==1.15.0
cloudpickle==2.1.0
cycler==0.11.0
fonttools==4.33.3
gym==0.24.0
gym-notices==0.0.6
importlib-metadata==4.11.4
kiwisolver==1.4.2
matplotlib==3.5.2
numpy==1.22.4
packaging==21.3
pandas==1.4.2
Pillow==9.1.1
pycparser==2.21
pygame==2.1.0
pymunk==6.2.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.1
six==1.16.0
stable-baselines3==1.5.0
tinyscaler==1.2.4
torch==1.11.0
typing-extensions==4.2.0
zipp==3.8.0

Supersuit from [here](https://github.com/jjshoots/SuperSuit/tree/master), and PettingZoo from the master branch.

**Comment by erickrf** [comment] 2022-05-30 23:03
I tried to install that environment with pipenv and plain pip, but it failed because of conflicts (MacOS 12.4):

```
    The user requested gym==0.24.0
    stable-baselines3 1.5.0 depends on gym==0.21
```

**Comment by erickrf** [comment] 2022-05-30 23:07
On a related note, using my existing environment (`ss` 3.4.0 and `pettingzoo` 1.18.1) I tried to learn a TicTacToe police:

```
from pettingzoo.classic import tictactoe_v3
from stable_baselines3 import PPO
from stable_baselines3.ppo import CnnPolicy

env = tictactoe_v3.env()
model = PPO(CnnPolicy, env)
model.learn(total_timesteps=200)
```

The error suggests some mismatch in expected interfaces... or am I missing some wrapper here?

```
Traceback (most recent call last):
  File "/Users/erick/dev/rl/main_pettingzoo.py", line 7, in <module>
    model = PPO(CnnPolicy, env)
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 94, in __init__
    super(PPO, self).__init__(
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 77, in __init__
    super(OnPolicyAlgorithm, self).__init__(
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 160, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 200, in _wrap_env
    env = DummyVecEnv([lambda: env])
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 29, in __init__
    self.keys, shapes, dtypes = obs_space_info(obs_space)
  File "/Users/erick/.local/share/virtualenvs/rl-0i49mzF7/lib/python3.9/site-packages/stable_baselines3/common/vec_env/util.py", line 74, in obs_space_info
    shapes[key] = box.shape
AttributeError: 'function' object has no attribute 'shape'
```

**Comment by benblack769** [comment] 2022-05-31 00:08
@erickrf Stable baselines can only train parallel pettingzoo environments which have been transformed into vector environments through the `pettingzoo_env_to_vec_env_v1` wrapper (see the tutorial).

Tictactoe is a turn-based game, so it cannot be transformed into a parallel environment through the standard means, and so we don't recomend training it with SB3, although in theory it can be turned into a parallel environment through the `turn_based_aec_to_parallel_wrapper` wrapper in `pettingzoo.utils.conversions` (but you should be aware of what that wrapper does before using it.

If you want a really simple environment to test your code on, I would recomend `pettingzoo.mpe.simple_spread_v2`.

**Comment by benblack769** [comment] 2022-05-31 00:09
As for your original problem with ProcCatEnv, this is a complicated multiprocessing wrapper that is hard to debug, and hard technically to generate good error messages for, although I have put some effort into that. I would recomend changing the tutorial to set the number of cpus to 1 to debug this:

```
env = ss.concat_vec_envs_v1(env, 8, num_cpus=1, base_class="stable_baselines3")
```

**Comment by jjshoots** [comment] 2022-06-02 17:41
Hey @erickrf, has there been any movement on this front?

**Comment by erickrf** [comment] 2022-06-03 20:50
Well, I tried to run a debugger and found out it was just taking a lot of time in the call to `collect_rollout`, and without any logging I had no idea of knowing. It still crashes if use more than one cpu core.

**Comment by jjshoots** [comment] 2022-06-05 12:44
@benblack769 any ideas?

**Comment by engyasin** [comment] 2022-08-08 11:47
I have the same original issue but on windows,
with 1 cpu, it worked but with very slow training. After I comment the training line it rendered correctly

**Comment by jjshoots** [comment] 2022-08-08 11:59
Hi @engyasin

Unfortunately, at the current moment, the ProcConcatVecEnv is a complicated wrapper that is designed and intended to be used on Linux machines only. It being slow is probably a consequence of it working only with 1 cpu thread. Although this is not something we're looking to solve immediately, its fix is definitely somewhere on the roadmap. If, however, you're able to figure out ways to make it work better, we accept PRs addressing this issue.

**Comment by benblack769** [comment] 2022-08-13 19:09
You can try to make the original error go away by putting the code in an `if __name__ == "__main__"` guard, as the error suggests:

This would look like this:

```
import supersuit as ss
from stable_baselines3 import PPO
from stable_baselines3.ppo import CnnPolicy

from pettingzoo.butterfly import pistonball_v6

def main():
	env = pistonball_v6.parallel_env(
		n_pistons=20,
		time_penalty=-0.1,
		continuous=True,
		random_drop=True,
		random_rotate=True,
		ball_mass=0.75,
		ball_friction=0.3,
		ball_elasticity=1.5,
		max_cycles=125,
	)
	env = ss.color_reduction_v0(env, mode="B")
	env = ss.resize_v1(env, x_size=84, y_size=84)
	env = ss.frame_stack_v1(env, 3)
	env = ss.pettingzoo_env_to_vec_env_v1(env)
	env = ss.concat_vec_envs_v1(env, 8, num_cpus=4, base_class="stable_baselines3")
	model = PPO(
		CnnPolicy,
		env,
		verbose=3,
		gamma=0.95,
		n_steps=256,
		ent_coef=0.0905168,
		learning_rate=0.00062211,
		vf_coef=0.042202,
		max_grad_norm=0.9,
		gae_lambda=0.99,
		n_epochs=5,
		clip_range=0.3,
		batch_size=256,
	)
	model.learn(total_timesteps=2000000)
	model.save("policy")

	# Rendering

	env = pistonball_v6.env()
	env = ss.color_reduction_v0(env, mode="B")
	env = ss.resize_v1(env, x_size=84, y_size=84)
	env = ss.frame_stack_v1(env, 3)

	model = PPO.load("policy")

	env.reset()
	for agent in env.agent_iter():
		obs, reward, done, info = env.last()
		act = model.predict(obs, deterministic=True)[0] if not done else None
		env.step(act)
		env.render()
		
if __name__ == "__main__":
	main()
```

**Comment by benblack769** [comment] 2022-08-13 19:10
^ have not tested this, again, we don't have official windows support, I haven't figured out how to install all the dependencies on windows.

**Comment by engyasin** [comment] 2022-08-14 16:36
Great,
Looks like its training now. (very slow in cpu)

**Comment by jjshoots** [comment] 2022-08-14 18:22
Thanks @benblack769 :)

**Closed by jjshoots** 2022-08-14 18:22 UTC
