### ISSUE TITLE
[Bug Report] Cannot import package: circular import with pettingzoo and gymnasium-robotics

### ISSUE THREAD

**Issue by thomasbbrunner** [Farama-Foundation/PettingZoo#1099] opened 2023-09-11 11:11 UTC
### Describe the bug

Importing `pettingzoo` crashes when the package `gymnasium-robotics` is installed in the system.

Code to reproduce behavior is included below. It consists of installing both packages and importing pettingzoo.

### Code example

```shell
# Install dependencies
pip install pettingzoo gymnasium-robotics

# Import pettingzoo in Python
>>> import pettingzoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pettingzoo/__init__.py", line 4, in <module>
    from pettingzoo.utils import AECEnv, ParallelEnv
  File "/usr/local/lib/python3.9/dist-packages/pettingzoo/utils/__init__.py", line 2, in <module>
    from pettingzoo.utils.average_total_reward import average_total_reward
  File "/usr/local/lib/python3.9/dist-packages/pettingzoo/utils/average_total_reward.py", line 7, in <module>
    from pettingzoo.utils.env import AECEnv
  File "/usr/local/lib/python3.9/dist-packages/pettingzoo/utils/env.py", line 6, in <module>
    import gymnasium.spaces
  File "/usr/local/lib/python3.9/dist-packages/gymnasium/__init__.py", line 12, in <module>
    from gymnasium.envs.registration import (
  File "/usr/local/lib/python3.9/dist-packages/gymnasium/envs/__init__.py", line 387, in <module>
    load_plugin_envs()
  File "/usr/local/lib/python3.9/dist-packages/gymnasium/envs/registration.py", line 592, in load_plugin_envs
    fn = plugin.load()
  File "/usr/local/lib/python3.9/dist-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/gymnasium_robotics/__init__.py", line 6, in <module>
    from gymnasium_robotics.envs.multiagent_mujoco import mamujoco_v0
  File "/usr/local/lib/python3.9/dist-packages/gymnasium_robotics/envs/multiagent_mujoco/__init__.py", line 12, in <module>
    from gymnasium_robotics.envs.multiagent_mujoco.mujoco_multi import (  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/gymnasium_robotics/envs/multiagent_mujoco/mujoco_multi.py", line 59, in <module>
    class MultiAgentMujocoEnv(pettingzoo.utils.env.ParallelEnv):
AttributeError: partially initialized module 'pettingzoo' has no attribute 'utils' (most likely due to a circular import)

# Works if gymnasium robotics is imported first (new Python instance)
>>> import gymnasium_robotics
>>> import pettingzoo
>>>
```

### System info

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```
```
gymnasium-robotics   1.2.2
pettingzoo           1.24.1
```
```
Python 3.9.15
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment] 2023-09-12 19:49
Hey, sorry about this, we’ve had issues like that with other Farama packages before and it’s a bit tricky to fix. I will try to get help from some other core devs and get it solved soon.

**Comment by pseudo-rnd-thoughts** [comment] 2023-09-12 21:46
This is an issue with Gymansium that was deprecated in v0.29 and will be removed in v1.0.0 
We aim to release v1.0.0 quite soon but it will require projects to update 

In the meantime, you will need to have that import order

**Comment by elliottower** [comment] 2023-09-13 14:03
FWIW we are planning to update PettingZoo and Shimmy and SuperSuit soon after gymnasium’s release in order to ensure compatibility. We can keep this open until then though.

**Comment by elliottower** [comment] 2023-09-27 19:17
Closing this now because it's not a bug with our library

**Closed by elliottower** 2023-09-27 19:17 UTC
Labels: bug
