### ISSUE TITLE
Hanabi v5 agent death without raising flag

### ISSUE THREAD

**Issue by FBredell** [Farama-Foundation/PettingZoo#1085] opened 2023-09-06 08:42 UTC
### Describe the bug

Good day,

I've noticed some strange behavior in the latest release of the Hanabi environment part of the classic environments (Hanabi v5). When an agent takes a similar action (or a no action) over the course of the episode the environment eventually terminates, my guess is that there is some behind the scenes turn limit implemented to stop games running too long. However, the flag for agent termination is never raised i.e. env.terminations remain False for each player. If an agent then tries to take an action the environment raises an error stating the agent has been terminated (dead), but the termination flags remain unchanged. Here is a snippet as example: 

![Screenshot from 2023-09-06 10-33-55](https://github.com/Farama-Foundation/PettingZoo/assets/80692702/5f91196f-62df-4723-923b-370fc9026c27)

This problem only started occurring when the environment updated from v4 to v5. 

Thank you in advance.

### System info

pettingzoo version - 1.24.1
python version - 3.10.9 
linux version - Ubuntu 22.04.3

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment] 2023-09-06 17:47
Thanks for raising this issue, we did a good amount of testing but somehow missed this problem, will push a hotfix to fix it soon

**Comment by elliottower** [comment] 2023-09-06 18:30
Could you give a script to reproduce the issue in case I can't reproduce it locally?

**Comment by elliottower** [comment] 2023-09-07 00:33
My guess is that this is occurring because you are using an irregular game loop logic, try this usage code to see if you still get the issue: 
```from pettingzoo.classic import hanabi_v5

env = hanabi_v5.env(render_mode="human")
env.reset(seed=42)

for agent in env.agent_iter():
    observation, reward, termination, truncation, info = env.last()

    if termination or truncation:
        action = None
    else:
        mask = observation["action_mask"]
        # this is where you would insert your policy
        action = env.action_space(agent).sample(mask)

    env.step(action)
env.close()
``` (from the environment's documentation page, usage section: https://pettingzoo.farama.org/environments/classic/hanabi/#aec)

I did some local testing and could not reproduce this, I did find a bug where the environment did not render by default though so I have fixed that. Accessing the environment's `terminations` and other internal dicts directly is not recommended, you should instead use the standard API calls such as `observation, rewards, termination, truncation, info = env.last(action)` for AEC envs and `observations, rewards, terminations, truncations, infos = env.step(actions)` for parallel envs.

**Comment by elliottower** [comment] 2023-09-07 19:28
Closing this, feel free to re-open if you see these messages and are still having the issue.

**Closed by elliottower** 2023-09-07 19:28 UTC
Labels: bug
